dbt:
  outputs:
    prod:
      type: sqlite
      threads: 1
      database: <database name>
      schema: 'main'
      schemas_and_paths:
        main: '../_data/data.sqlite3'
      schema_directory: '../_data'
  target: prod
